/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "log_rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
registrar_operacion_1(log_request arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, REGISTRAR_OPERACION,
		(xdrproc_t) xdr_log_request, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
