/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "log_rpc.h"

bool_t
xdr_log_request (XDR *xdrs, log_request *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->usuario, MAX_USER_LEN))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operacion, MAX_OP_LEN))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->fichero, MAX_FILE_LEN))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tiene_fichero))
		 return FALSE;
	return TRUE;
}
