/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOG_RPC_H_RPCGEN
#define _LOG_RPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MAX_USER_LEN 256
#define MAX_OP_LEN 32
#define MAX_FILE_LEN 256

struct log_request {
	char *usuario;
	char *operacion;
	char *fichero;
	int tiene_fichero;
};
typedef struct log_request log_request;

#define LOG_RPC_PROG 99
#define LOG_RPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define REGISTRAR_OPERACION 1
extern  enum clnt_stat registrar_operacion_1(log_request , int *, CLIENT *);
extern  bool_t registrar_operacion_1_svc(log_request , int *, struct svc_req *);
extern int log_rpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REGISTRAR_OPERACION 1
extern  enum clnt_stat registrar_operacion_1();
extern  bool_t registrar_operacion_1_svc();
extern int log_rpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_log_request (XDR *, log_request*);

#else /* K&R C */
extern bool_t xdr_log_request ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOG_RPC_H_RPCGEN */
